project:
  type: website

website:
  title: <strong>Frato</strong>
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



