project:
  type: website

website:
  title: <strong>Steven Frato</strong>
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - href: projects.qmd
        text: Projects
      - href: media.qmd
        text: Media

format:
  html:
    theme: pulse
    css: styles.css
    toc: false